### ISSUE TITLE
The process was terminated due to an unhandled exception

### ISSUE THREAD

**Issue by dw-andrewsfasteners** [DRN88/HotFolderPrinterFoxitPdf#4]
I am experiencing random crashes of an app.
Will you be able to help.

Some information from **Event Viewer** on Windows 11:

_Source: .NET Runtime_
```
Application: HotFolderPrinterFoxitPdf.exe
CoreCLR Version: 6.0.3324.36610
.NET Version: 6.0.33
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at HotFolderPrinterFoxitPdf.frmMainForm1.ScanQueueDirAndPrintPDFDocuments() in C:\HotFolderPrinterFoxitPdf-andrews\frmMainForm1.cs:line 80
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

XML View:
```
[-](https://github.com/DRN88/HotFolderPrinterFoxitPdf/issues/new#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/DRN88/HotFolderPrinterFoxitPdf/issues/new#) <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-09-19T09:44:18.8796077Z" /> 
  <EventRecordID>64590</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="20440" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Computer90[-](https://github.com/DRN88/HotFolderPrinterFoxitPdf/issues/new#)2023B</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: HotFolderPrinterFoxitPdf.exe CoreCLR Version: 6.0.3324.36610 .NET Version: 6.0.33 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.IOException: The process cannot access the file because it is being used by another process. at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite) at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite) at HotFolderPrinterFoxitPdf.frmMainForm1.ScanQueueDirAndPrintPDFDocuments() in C:\HotFolderPrinterFoxitPdf-andrews\frmMainForm1.cs:line 80 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool) at System.Threading.TimerQueue.FireNextTimers()</Data> 
  </EventData>
  </Event>
```

_Source: Application Error_
```
Faulting application name: HotFolderPrinterFoxitPdf.exe, version: 1.0.0.0, time stamp: 0x66960000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4111, time stamp: 0x03c619d0
Exception code: 0xe0434352
Fault offset: 0x000000000005fabc
Faulting process id: 0x0x4FD8
Faulting application start time: 0x0x1DB0A65FC780680
Faulting application path: C:\HotFolders\HotFolderPrinterFoxitPdf.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: a990ba79-00c2-435d-abc1-31edbaf123ca
Faulting package full name: 
Faulting package-relative application ID: 
```

XML View:
```
[-](https://github.com/DRN88/HotFolderPrinterFoxitPdf/issues/new#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/DRN88/HotFolderPrinterFoxitPdf/issues/new#) <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2024-09-19T09:44:19.1484577Z" /> 
  <EventRecordID>64591</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="15544" ThreadID="18884" /> 
  <Channel>Application</Channel> 
  <Computer>Computer90-2023B</Computer> 
  <Security UserID="S[-](https://github.com/DRN88/HotFolderPrinterFoxitPdf/issues/new#)1-12-1-3191215926-1245759033-3052173241-1028132257" /> 
  </System>
- <EventData>
  <Data Name="AppName">HotFolderPrinterFoxitPdf.exe</Data> 
  <Data Name="AppVersion">1.0.0.0</Data> 
  <Data Name="AppTimeStamp">66960000</Data> 
  <Data Name="ModuleName">KERNELBASE.dll</Data> 
  <Data Name="ModuleVersion">10.0.22621.4111</Data> 
  <Data Name="ModuleTimeStamp">03c619d0</Data> 
  <Data Name="ExceptionCode">e0434352</Data> 
  <Data Name="FaultingOffset">000000000005fabc</Data> 
  <Data Name="ProcessId">0x4fd8</Data> 
  <Data Name="ProcessCreationTime">0x1db0a65fc780680</Data> 
  <Data Name="AppPath">C:\HotFolders\HotFolderPrinterFoxitPdf.exe</Data> 
  <Data Name="ModulePath">C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data Name="IntegratorReportId">a990ba79-00c2-435d-abc1-31edbaf123ca</Data> 
  <Data Name="PackageFullName" /> 
  <Data Name="PackageRelativeAppId" /> 
  </EventData>
  </Event>
```

**Comment by DRN88** [comment]
This can happen if multiple instance is running. I just fixed this by allowing only one running instance.
Clone the repo and Rebuild and you are good to go.

**Comment by dw-andrewsfasteners** [comment]
Thank you.
